use crate::NN::NN;
use crate::ZZ::ZZ;
use koto_runtime::{Result, derive::*, prelude::*};

use algebraeon::nzq::{Integer, Natural};
use algebraeon::nzq::traits::DivMod;
use algebraeon::sets::structure::EqSignature;
use algebraeon_rings::structure::{
    AdditionSignature, IdealsArithmeticSignature, MetaCanonicalIdealsSignature,
    MultiplicationSignature,
};

/// Converts a koto value into an Integer (accepts i64 Number, NN and ZZ).
fn integer_from_value(value: &KValue) -> Result<Integer> {
    match value {
        KValue::Number(n) if n.is_i64() => Ok(Integer::from(i64::from(*n))),
        KValue::Object(object) => {
            if let Ok(nn) = object.cast::<NN>() {
                Ok(Integer::from(nn.0.clone()))
            } else if let Ok(zz) = object.cast::<ZZ>() {
                Ok(zz.to_integer())
            } else {
                unexpected_type("Number, NN, or ZZ", value)
            }
        }
        unexpected => unexpected_type("Number, NN, or ZZ", unexpected),
    }
}

/// An ideal of ZZ, backed by algebraeon's `IntegerIdealsStructure`.
///
/// Ideals of ZZ are principal, so an ideal is stored by its canonical
/// non-negative generator: Ideal(6) = 6Z and Ideal(4, 6) = gcd(4, 6)Z = 2Z.
/// Display format: "nZ" where n is the canonical generator (e.g. 6Z, 0Z).
#[derive(PartialEq, Clone, KotoCopy, KotoType, Eq, Debug)]
pub struct Ideal(pub Natural);

#[koto_impl]
impl Ideal {
    /// Ideal(enters...) — the ideal of ZZ generated by the given integers
    /// (NN/ZZ/Number). Ideal(6) = 6Z; Ideal(4, 6) = gcd(4, 6)Z = 2Z.
    pub fn from_args(args: &[KValue]) -> Result<KValue> {
        let mut elems = Vec::with_capacity(args.len());
        for arg in args {
            elems.push(integer_from_value(arg)?);
        }
        let generator = Integer::ideals().generated_ideal(elems);
        Ok(KValue::Object(KObject::from(Self(generator))))
    }

    /// Does the ideal contain n (n can be NN/ZZ/Number)?
    #[koto_method]
    pub fn contains(&self, args: &[KValue]) -> Result<KValue> {
        match args {
            [n] => {
                let x = integer_from_value(n)?;
                let contains = if self.0 == Natural::ZERO {
                    // 0Z = {0}: only 0 belongs to it
                    x == Integer::ZERO
                } else {
                    Integer::ideals().contains_element(&self.0, &x)
                };
                Ok(contains.into())
            }
            unexpected => unexpected_args("|Number|", unexpected),
        }
    }

    /// The canonical non-negative generator of the ideal (an NN).
    #[koto_method]
    pub fn generator(&self) -> KValue {
        KValue::Object(KObject::from(NN(self.0.clone())))
    }

    /// Sum of two ideals: (aZ + bZ) = gcd(a, b)Z.
    #[koto_method]
    pub fn sum(&self, args: &[KValue]) -> Result<KValue> {
        match args {
            [KValue::Object(other)] if other.is_a::<Self>() => {
                let other = other.cast::<Self>().unwrap();
                let generator = Integer::ideals().add(&self.0, &other.0);
                Ok(KValue::Object(KObject::from(Self(generator))))
            }
            unexpected => unexpected_args("|Ideal|", unexpected),
        }
    }

    /// Intersection of two ideals: (aZ ∩ bZ) = lcm(a, b)Z.
    #[koto_method]
    pub fn intersect(&self, args: &[KValue]) -> Result<KValue> {
        match args {
            [KValue::Object(other)] if other.is_a::<Self>() => {
                let other = other.cast::<Self>().unwrap();
                let generator = Integer::ideals().intersect(&self.0, &other.0);
                Ok(KValue::Object(KObject::from(Self(generator))))
            }
            unexpected => unexpected_args("|Ideal|", unexpected),
        }
    }

    /// Product of two ideals: (aZ)(bZ) = (ab)Z.
    #[koto_method]
    pub fn product(&self, args: &[KValue]) -> Result<KValue> {
        match args {
            [KValue::Object(other)] if other.is_a::<Self>() => {
                let other = other.cast::<Self>().unwrap();
                let generator = Integer::ideals().mul(&self.0, &other.0);
                Ok(KValue::Object(KObject::from(Self(generator))))
            }
            unexpected => unexpected_args("|Ideal|", unexpected),
        }
    }

    /// Ideal quotient (I : J) = { x in ZZ : xJ ⊆ I }.
    #[koto_method]
    pub fn quotient(&self, args: &[KValue]) -> Result<KValue> {
        match args {
            [KValue::Object(other)] if other.is_a::<Self>() => {
                let other = other.cast::<Self>().unwrap();
                let generator = Integer::ideals().quotient(&self.0, &other.0);
                Ok(KValue::Object(KObject::from(Self(generator))))
            }
            unexpected => unexpected_args("|Ideal|", unexpected),
        }
    }

    /// Ideal equality (same canonical generator).
    #[koto_method]
    pub fn equals(&self, args: &[KValue]) -> Result<KValue> {
        match args {
            [KValue::Object(other)] if other.is_a::<Self>() => {
                let other = other.cast::<Self>().unwrap();
                Ok(Integer::ideals().equal(&self.0, &other.0).into())
            }
            unexpected => unexpected_args("|Ideal|", unexpected),
        }
    }
}

impl KotoObject for Ideal {
    fn equal(&self, other: &KValue) -> Result<bool> {
        match other {
            KValue::Object(other) if other.is_a::<Self>() => {
                let other = other.cast::<Self>().unwrap();
                Ok(Integer::ideals().equal(&self.0, &other.0))
            }
            unexpected => unexpected_type("Ideal", unexpected),
        }
    }

    fn display(&self, ctx: &mut DisplayContext) -> koto_runtime::Result<()> {
        ctx.append(format!("{}Z", self.0));
        Ok(())
    }
}

/// Extended Euclidean algorithm: returns the inverse of `a` modulo `m`
/// (normalized into [0, m)) or None when gcd(a, m) != 1.
///
/// Assumes m > 0 and 0 <= a < m; all divisions use `div_mod` with positive
/// divisors, so every remainder stays non-negative and the standard
/// non-negative Euclidean algorithm applies.
fn inverse_mod(a: &Integer, m: &Integer) -> Option<Integer> {
    let mut r0 = a.clone();
    let mut r1 = m.clone();
    let mut s0 = Integer::ONE;
    let mut s1 = Integer::ZERO;
    while r1 != Integer::ZERO {
        let (q, r) = r0.clone().div_mod(r1.clone());
        r0 = r1;
        r1 = r;
        let s = s0.clone() - q * s1.clone();
        s0 = s1;
        s1 = s;
    }
    if r0 == Integer::ONE {
        // s0 is a Bezout coefficient of gcd(a, m) = 1: s0*a ≡ 1 (mod m).
        // Normalize the inverse into [0, m).
        let (_q, r) = s0.div_mod(m.clone());
        Some(r)
    } else {
        None
    }
}

/// The ring ZZ/nZZ of integers modulo n. ZZn(n) builds the ring for a
/// positive modulus n; ZZn(n).of(x) returns the class of x (a ZZnElement).
#[derive(PartialEq, Clone, KotoCopy, KotoType, Eq, Debug)]
pub struct ZZn {
    modulus: Integer,
}

#[koto_impl]
impl ZZn {
    /// ZZn(n) — the ring ZZ/nZZ with modulus n > 0 (NN/ZZ/Number).
    pub fn from_args(args: &[KValue]) -> Result<KValue> {
        match args {
            [n] => {
                let modulus = integer_from_value(n)?;
                if modulus <= Integer::ZERO {
                    return runtime_error!("ZZn: modulus must be positive, got {}", modulus);
                }
                Ok(KValue::Object(KObject::from(Self { modulus })))
            }
            unexpected => unexpected_args("|Number|", unexpected),
        }
    }

    /// The class of x modulo n (x can be NN/ZZ/Number).
    #[koto_method]
    pub fn of(&self, args: &[KValue]) -> Result<KValue> {
        match args {
            [x] => {
                let value = integer_from_value(x)?;
                // div_mod with a positive modulus yields 0 <= r < n.
                let (_q, r) = value.div_mod(self.modulus.clone());
                Ok(KValue::Object(KObject::from(ZZnElement {
                    modulus: self.modulus.clone(),
                    value: r,
                })))
            }
            unexpected => unexpected_args("|Number|", unexpected),
        }
    }
}

impl KotoObject for ZZn {
    fn equal(&self, other: &KValue) -> Result<bool> {
        match other {
            KValue::Object(other) if other.is_a::<Self>() => {
                let other = other.cast::<Self>().unwrap();
                Ok(self.modulus == other.modulus)
            }
            unexpected => unexpected_type("ZZn", unexpected),
        }
    }

    fn display(&self, ctx: &mut DisplayContext) -> koto_runtime::Result<()> {
        ctx.append("ZZn");
        Ok(())
    }
}

/// A residue class [x] in ZZ/nZZ, stored with its canonical representative
/// 0 <= x < n. Display format: "[x] mod n".
#[derive(PartialEq, Clone, KotoCopy, KotoType, Eq, Debug)]
pub struct ZZnElement {
    modulus: Integer,
    value: Integer,
}

#[koto_impl]
impl ZZnElement {
    /// Multiplicative inverse of the class (errors when not coprime with n).
    #[koto_method]
    pub fn inverse(&self) -> Result<KValue> {
        match inverse_mod(&self.value, &self.modulus) {
            Some(inv) => Ok(KValue::Object(KObject::from(Self {
                modulus: self.modulus.clone(),
                value: inv,
            }))),
            None => runtime_error!(
                "ZZn: {} has no inverse modulo {} (not coprime with the modulus)",
                self.value,
                self.modulus
            ),
        }
    }
}

impl KotoObject for ZZnElement {
    fn equal(&self, other: &KValue) -> Result<bool> {
        match other {
            KValue::Object(other) if other.is_a::<Self>() => {
                let other = other.cast::<Self>().unwrap();
                Ok(self.modulus == other.modulus && self.value == other.value)
            }
            unexpected => unexpected_type("ZZnElement", unexpected),
        }
    }

    fn add(&self, other: &KValue) -> Result<KValue> {
        match other {
            KValue::Object(other) if other.is_a::<Self>() => {
                let other = other.cast::<Self>().unwrap();
                if self.modulus != other.modulus {
                    return runtime_error!(
                        "ZZn: cannot add classes with different moduli {} and {}",
                        self.modulus,
                        other.modulus
                    );
                }
                let (_q, r) =
                    (self.value.clone() + other.value.clone()).div_mod(self.modulus.clone());
                Ok(KValue::Object(KObject::from(Self {
                    modulus: self.modulus.clone(),
                    value: r,
                })))
            }
            unexpected => unexpected_type("ZZnElement", unexpected),
        }
    }

    fn subtract(&self, other: &KValue) -> Result<KValue> {
        match other {
            KValue::Object(other) if other.is_a::<Self>() => {
                let other = other.cast::<Self>().unwrap();
                if self.modulus != other.modulus {
                    return runtime_error!(
                        "ZZn: cannot subtract classes with different moduli {} and {}",
                        self.modulus,
                        other.modulus
                    );
                }
                let (_q, r) =
                    (self.value.clone() - other.value.clone()).div_mod(self.modulus.clone());
                Ok(KValue::Object(KObject::from(Self {
                    modulus: self.modulus.clone(),
                    value: r,
                })))
            }
            unexpected => unexpected_type("ZZnElement", unexpected),
        }
    }

    fn multiply(&self, other: &KValue) -> Result<KValue> {
        match other {
            KValue::Object(other) if other.is_a::<Self>() => {
                let other = other.cast::<Self>().unwrap();
                if self.modulus != other.modulus {
                    return runtime_error!(
                        "ZZn: cannot multiply classes with different moduli {} and {}",
                        self.modulus,
                        other.modulus
                    );
                }
                let (_q, r) =
                    (self.value.clone() * other.value.clone()).div_mod(self.modulus.clone());
                Ok(KValue::Object(KObject::from(Self {
                    modulus: self.modulus.clone(),
                    value: r,
                })))
            }
            unexpected => unexpected_type("ZZnElement", unexpected),
        }
    }

    fn negate(&self) -> Result<KValue> {
        let (_q, r) = (-self.value.clone()).div_mod(self.modulus.clone());
        Ok(KValue::Object(KObject::from(Self {
            modulus: self.modulus.clone(),
            value: r,
        })))
    }

    fn display(&self, ctx: &mut DisplayContext) -> koto_runtime::Result<()> {
        ctx.append(format!("[{}] mod {}", self.value, self.modulus));
        Ok(())
    }
}
