use crate::NN::NN;
use koto_runtime::{Result, derive::*, prelude::*};

use algebraeon::nzq::Integer;
use algebraeon::nzq::traits::{Abs, DivMod};
use algebraeon_rings::structure::{
    IdealsArithmeticSignature, MetaCanonicalIdealsSignature, MetaFactoringMonoid,
};

#[derive(PartialEq, Clone, KotoCopy, KotoType, Eq, Debug)]
pub struct ZZ(Integer);

#[koto_impl]
impl ZZ {
    pub fn from_integer(i: Integer) -> Self {
        Self(i)
    }

    pub fn to_integer(&self) -> Integer {
        self.0.clone()
    }

    pub fn make_koto_object(n: KNumber) -> KObject {
        let my_int = Integer::from(i64::from(n));
        KObject::from(Self(my_int))
    }

    #[koto_method]
    pub fn abs(&self) -> KValue {
        KValue::Object(KObject::from(NN::from(NN(self.0.clone().abs()))))
    }

    #[koto_method]
    pub fn is_irreducible(&self) -> KValue {
        self.0.is_irreducible().into()
    }

    #[koto_method]
    pub fn is_square(&self) -> KValue {
        self.0.is_square().into()
    }

    /// The ideal of ZZ generated by this integer: ZZ(3).ideal() = Ideal(3) = 3Z.
    #[koto_method]
    pub fn ideal(&self) -> KValue {
        let generator = Integer::ideals().generated_ideal(vec![self.0.clone()]);
        KValue::Object(KObject::from(crate::Ideal::Ideal(generator)))
    }

    #[koto_method]
    pub fn factor(&self) -> KValue {
        match self.0.clone().factor().into_powers() {
            Some(factors) => {
                let koto_factors: Vec<KValue> = factors
                    .into_iter()
                    .map(|(prime, exp)| {
                        let prime_val = KValue::Object(KObject::from(ZZ(prime)));
                        let exp_val = KValue::Object(KObject::from(NN(exp)));
                        KValue::Tuple(vec![prime_val, exp_val].into())
                    })
                    .collect();

                KValue::List(KList::with_data(koto_factors.into()))
            }
            None => KValue::Null,
        }
    }

    #[koto_method]
    pub fn divmod(&self, args: &[KValue]) -> Result<KValue> {
        match args {
            [KValue::Object(other)] if other.is_a::<ZZ>() => {
                let other = other.cast::<ZZ>().unwrap();
                let (q, r) = self.0.clone().div_mod(other.0.clone());
                Ok(KValue::Tuple(
                    vec![
                        KValue::Object(KObject::from(ZZ(q))),
                        KValue::Object(KObject::from(ZZ(r))),
                    ]
                    .into(),
                ))
            }
            unexpected => unexpected_args("|ZZ|", unexpected),
        }
    }

    #[koto_method]
    pub fn div_floor(&self, args: &[KValue]) -> Result<KValue> {
        match args {
            [KValue::Object(other)] if other.is_a::<ZZ>() => {
                let other = other.cast::<ZZ>().unwrap();
                let (q, _r) = self.0.clone().div_mod(other.0.clone());
                Ok(KValue::Object(KObject::from(ZZ(q))))
            }
            unexpected => unexpected_args("|ZZ|", unexpected),
        }
    }

    #[koto_method(alias = "mod")]
    pub fn modulo(&self, args: &[KValue]) -> Result<KValue> {
        match args {
            [KValue::Object(other)] if other.is_a::<ZZ>() => {
                let other = other.cast::<ZZ>().unwrap();
                let (_q, r) = self.0.clone().div_mod(other.0.clone());
                // div_mod returns a remainder with the same sign as the divisor;
                // adjust it to be a non-negative remainder (coherent with div_floor
                // for positive divisors).
                let r = if r < Integer::ZERO {
                    r + Integer::from(other.0.clone().abs())
                } else {
                    r
                };
                Ok(KValue::Object(KObject::from(ZZ(r))))
            }
            unexpected => unexpected_args("|ZZ|", unexpected),
        }
    }
}

impl KotoObject for ZZ {
    fn add(&self, other: &KValue) -> Result<KValue> {
        match other {
            KValue::Object(other) if other.is_a::<Self>() => {
                let other = other.cast::<Self>().unwrap();
                let result = self.0.clone() + other.0.clone();
                Ok(KValue::Object(KObject::from(Self(result))))
            }
            KValue::Object(other) if other.is_a::<NN>() => {
                let other = other.cast::<NN>().unwrap();
                let result = self.0.clone() + Integer::from(other.clone().0);
                Ok(KValue::Object(KObject::from(Self(result))))
            }
            KValue::Number(other) if other.is_i64() => {
                let result = ZZ(self.0.clone() + Integer::from(i64::from(other)));
                Ok(KValue::Object(KObject::from(result)))
            }
            unexpected => unexpected_type("ZZ", unexpected),
        }
    }

    fn display(&self, ctx: &mut DisplayContext) -> koto_runtime::Result<()> {
        ctx.append(self.0.to_string());
        Ok(())
    }

    fn equal(&self, other: &KValue) -> Result<bool> {
        match other {
            KValue::Object(other) if other.is_a::<Self>() => {
                let other = other.cast::<Self>().unwrap();
                Ok(self.0 == other.0)
            }
            unexpected => unexpected_type("Number", unexpected),
        }
    }

    fn negate(&self) -> Result<KValue> {
        Ok(KValue::Object(KObject::from(Self(-self.0.clone()))))
    }

    fn multiply(&self, rhs: &KValue) -> Result<KValue> {
        match rhs {
            KValue::Object(other) if other.is_a::<Self>() => {
                let other = other.cast::<Self>().unwrap();
                let result = self.0.clone() * other.0.clone();
                Ok(KValue::Object(KObject::from(Self(result))))
            }
            unexpected => unexpected_type("ZZ", unexpected),
        }
    }

    fn subtract(&self, rhs: &KValue) -> Result<KValue> {
        match rhs {
            KValue::Object(other) if other.is_a::<Self>() => {
                let other = other.cast::<Self>().unwrap();
                let result = self.0.clone() - other.0.clone();
                Ok(KValue::Object(KObject::from(Self(result))))
            }
            unexpected => unexpected_type("ZZ", unexpected),
        }
    }

    fn add_assign(&mut self, other: &KValue) -> Result<()> {
        match other {
            KValue::Object(other) if other.is_a::<Self>() => {
                let other = other.cast::<Self>().unwrap();
                self.0 += other.0.clone();
                Ok(())
            }
            KValue::Object(other) if other.is_a::<NN>() => {
                let other = other.cast::<NN>().unwrap();
                self.0 += Integer::from(other.0.clone());
                Ok(())
            }
            KValue::Number(other) if other.is_i64() => {
                self.0 += Integer::from(i64::from(other));
                Ok(())
            }
            unexpected => unexpected_type("ZZ, NN, or Number", unexpected),
        }
    }

    fn multiply_assign(&mut self, other: &KValue) -> Result<()> {
        match other {
            KValue::Object(other) if other.is_a::<Self>() => {
                let other = other.cast::<Self>().unwrap();
                self.0 *= other.0.clone();
                Ok(())
            }
            KValue::Object(other) if other.is_a::<NN>() => {
                let other = other.cast::<NN>().unwrap();
                self.0 *= Integer::from(other.0.clone());
                Ok(())
            }
            KValue::Number(other) if other.is_i64() => {
                self.0 *= Integer::from(i64::from(other));
                Ok(())
            }
            unexpected => unexpected_type("ZZ, NN, or Number", unexpected),
        }
    }
}
